# Generated by Django 3.1.2 on 2020-12-08 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('applicationID', models.AutoField(primary_key=True, serialize=False)),
                ('matchingSkills', models.IntegerField()),
                ('dateApplied', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryType',
            fields=[
                ('categoryTypeID', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyID', models.AutoField(primary_key=True, serialize=False)),
                ('companyName', models.CharField(max_length=30)),
                ('companyDescription', models.CharField(max_length=250)),
                ('website', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=100)),
                ('twitter', models.CharField(max_length=100)),
                ('categoryTypeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.categorytype')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyEmployee',
            fields=[
                ('employeeID', models.AutoField(primary_key=True, serialize=False)),
                ('jobTitle', models.CharField(max_length=20)),
                ('companyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanySize',
            fields=[
                ('companySizeID', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='JobListings',
            fields=[
                ('jobListingID', models.AutoField(primary_key=True, serialize=False)),
                ('jobTitle', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('ZIP', models.IntegerField()),
                ('lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('long', models.DecimalField(decimal_places=8, max_digits=11)),
                ('jobDescription', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=15)),
                ('dateFilled', models.DateField()),
                ('categoryTypeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.categorytype')),
                ('companyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.company')),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.companyemployee')),
            ],
        ),
        migrations.CreateModel(
            name='JobOffers',
            fields=[
                ('jobOfferID', models.AutoField(primary_key=True, serialize=False)),
                ('startDate', models.DateField()),
                ('applicantResponse', models.CharField(max_length=15)),
                ('applicationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.applications')),
                ('jobListingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.joblistings')),
            ],
        ),
        migrations.CreateModel(
            name='MinorityType',
            fields=[
                ('minorityTypeID', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('personID', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=14)),
                ('DOB', models.DateField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('ZIP', models.IntegerField()),
                ('lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('long', models.DecimalField(decimal_places=8, max_digits=11)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('facebook', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=100)),
                ('twitter', models.CharField(max_length=100)),
                ('aboutMe', models.CharField(max_length=250)),
                ('jobExperience', models.CharField(max_length=250)),
                ('minorityTypeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.minoritytype')),
            ],
        ),
        migrations.CreateModel(
            name='PersonType',
            fields=[
                ('personTypeID', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Resumes',
            fields=[
                ('resumeID', models.AutoField(primary_key=True, serialize=False)),
                ('resumefile', models.FileField(upload_to='photos/')),
                ('uploadDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavedJobs',
            fields=[
                ('savedJobID', models.AutoField(primary_key=True, serialize=False)),
                ('dateSaved', models.DateField(auto_now=True)),
                ('jobListingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.joblistings')),
                ('personID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.person')),
            ],
        ),
        migrations.CreateModel(
            name='SkillLevel',
            fields=[
                ('skillLevelID', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.IntegerField()),
                ('applicationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.applications')),
                ('jobListingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.joblistings')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('skillID', models.AutoField(primary_key=True, serialize=False)),
                ('skillName', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='People',
        ),
        migrations.AddField(
            model_name='skilllevel',
            name='skillID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.skills'),
        ),
        migrations.AddField(
            model_name='person',
            name='personTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.persontype'),
        ),
        migrations.AddField(
            model_name='person',
            name='resumeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.resumes'),
        ),
        migrations.AddField(
            model_name='joboffers',
            name='resumeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.resumes'),
        ),
        migrations.AddField(
            model_name='joblistings',
            name='savedJobListings',
            field=models.ManyToManyField(through='login.SavedJobs', to='login.Person'),
        ),
        migrations.AddField(
            model_name='companyemployee',
            name='personID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.person'),
        ),
        migrations.AddField(
            model_name='company',
            name='companySizeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.companysize'),
        ),
        migrations.AddField(
            model_name='applications',
            name='jobListingID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.joblistings'),
        ),
        migrations.AddField(
            model_name='applications',
            name='personID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.person'),
        ),
        migrations.AddField(
            model_name='applications',
            name='resumeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.resumes'),
        ),
    ]
