# Generated by Django 3.1.2 on 2020-12-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20201209_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblistings',
            name='jobDescription',
            field=models.CharField(max_length=6000),
        ),
    ]
