# Generated by Django 3.1.2 on 2020-12-08 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20201208_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profilePic',
            field=models.FileField(null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='person',
            name='aboutMe',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='facebook',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='jobExperience',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='lat',
            field=models.DecimalField(decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='linkedin',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='long',
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='twitter',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
