# Generated by Django 3.1.2 on 2020-12-09 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20201209_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='personTypeID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.persontype'),
        ),
    ]
