# Generated by Django 3.1.2 on 2020-12-08 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20201208_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='minorityTypeID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.minoritytype'),
        ),
        migrations.AlterField(
            model_name='person',
            name='personTypeID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.persontype'),
        ),
        migrations.AlterField(
            model_name='person',
            name='resumeID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.resumes'),
        ),
    ]
