# Generated by Django 3.1.2 on 2020-12-08 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20201208_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='profilePic',
            field=models.FileField(null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='company',
            name='categoryTypeID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.categorytype'),
        ),
        migrations.AlterField(
            model_name='company',
            name='companyDescription',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='companySizeID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.companysize'),
        ),
        migrations.AlterField(
            model_name='company',
            name='facebook',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='linkedin',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='twitter',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='joblistings',
            name='dateFilled',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='joblistings',
            name='lat',
            field=models.DecimalField(decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='joblistings',
            name='long',
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='joblistings',
            name='status',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='joboffers',
            name='applicantResponse',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='skilllevel',
            name='applicationID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.applications'),
        ),
    ]
