# Generated by Django 3.1.2 on 2020-12-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20201208_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='companyDescription',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='companyName',
            field=models.CharField(max_length=70),
        ),
    ]
