# Generated by Django 3.1.2 on 2020-12-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20201208_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyemployee',
            name='jobTitle',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterModelTable(
            name='minoritytype',
            table='login_minoritytype',
        ),
    ]
