# Generated by Django 3.1.2 on 2020-12-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20201209_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profilePic',
            field=models.FileField(null=True, upload_to='img'),
        ),
    ]
