# Generated by Django 3.1.2 on 2020-12-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20201208_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytype',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
