# Generated by Django 3.1.2 on 2020-12-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20201209_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='companyName',
            field=models.CharField(max_length=70),
        ),
    ]
