# Generated by Django 3.1.2 on 2020-12-09 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20201209_1808'),
        ('login', '0012_auto_20201209_0335'),
    ]

    operations = [
    ]
