# Generated by Django 3.1.2 on 2020-12-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20201209_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='profilePic',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='person',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='resumes',
            name='resumefile',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
