# Generated by Django 3.1.2 on 2020-12-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_auto_20201209_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytype',
            name='type',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='companysize',
            name='size',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='joblistings',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='joboffers',
            name='applicantResponse',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
