# Generated by Django 3.1.2 on 2020-12-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_auto_20201209_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblistings',
            name='jobDescription',
            field=models.CharField(max_length=3000),
        ),
    ]
