# Generated by Django 3.1.2 on 2020-12-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_auto_20201209_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblistings',
            name='jobDescription',
            field=models.CharField(max_length=6000),
        ),
    ]
