# Generated by Django 3.1.2 on 2020-12-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_auto_20201209_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytype',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
